const players = [
  // ── FM 12 ──────────────────────────────────────────────────────────────
  {
    id: 1,
    name: "Yoann Gourcuff",
    team: "Olympique Lyonnais",
    nationality: "France",
    jerseyNumber: 8,
    age: 25,
    image: "https://r2.thesportsdb.com/images/media/player/cutout/919541.png",
    rating: 86,
    position: "CAM",
    cardType: "toty",
    flag: "🇫🇷",
    fmVersion: "FM12",
    stats: { PAC: 12, FIN: 15, PAS: 17, DRI: 17, VIS: 18, STR: 10 },
  },
  {
    id: 2,
    name: "Michel Bastos",
    team: "Olympique Lyonnais",
    nationality: "Brazil",
    jerseyNumber: 11,
    age: 28,
    image: "https://r2.thesportsdb.com/images/media/player/thumb/jsdyin1531688909.jpg",
    rating: 82,
    position: "LW",
    cardType: "gold",
    flag: "🇧🇷",
    fmVersion: "FM12",
    stats: { PAC: 16, FIN: 13, PAS: 15, DRI: 15, VIS: 14, STR: 13 },
  },
  {
    id: 3,
    name: "Lamine Gassama",
    team: "Lokomotiv Moscow",
    nationality: "Senegal",
    jerseyNumber: 2,
    age: 22,
    image: "https://r2.thesportsdb.com/images/media/player/cutout/34011685.png",
    rating: 77,
    position: "RB",
    cardType: "silver",
    flag: "🇸🇳",
    fmVersion: "FM12",
    stats: { PAC: 19, FIN: 8, PAS: 11, DRI: 13, VIS: 10, STR: 13 },
  },
  {
    id: 4,
    name: "Yann M'Vila",
    team: "Stade Rennais",
    nationality: "France",
    jerseyNumber: 6,
    age: 21,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Yann_M%27Vila_2017.jpg/330px-Yann_M%27Vila_2017.jpg",
    rating: 82,
    position: "DM",
    cardType: "hero",
    flag: "🇫🇷",
    fmVersion: "FM12",
    stats: { PAC: 13, FIN: 10, PAS: 15, DRI: 13, VIS: 14, STR: 17 },
  },
  {
    id: 5,
    name: "Jose Angel",
    team: "Atlético Madrid",
    nationality: "Spain",
    jerseyNumber: 3,
    age: 24,
    image: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Crespo2018.jpg",
    rating: 78,
    position: "LB",
    cardType: "silver",
    flag: "🇪🇸",
    fmVersion: "FM12",
    stats: { PAC: 15, FIN: 9, PAS: 13, DRI: 13, VIS: 12, STR: 14 },
  },
  {
    id: 6,
    name: "Cristiano Ronaldo",
    team: "Real Madrid",
    nationality: "Portugal",
    jerseyNumber: 7,
    age: 27,
    image: "https://r2.thesportsdb.com/images/media/player/cutout/a19jje1761592498.png",
    rating: 95,
    position: "LW",
    cardType: "gold",
    flag: "🇵🇹",
    fmVersion: "FM12",
    stats: { PAC: 19, FIN: 18, PAS: 15, DRI: 19, VIS: 15, STR: 17 },
  },
  {
    id: 22,
    name: "Marco Verratti",
    team: "Paris Saint-Germain",
    nationality: "Italy",
    jerseyNumber: 6,
    age: 19,
    image: "https://r2.thesportsdb.com/images/media/player/cutout/wgbjb91704625717.png",
    rating: 84,
    position: "CM",
    cardType: "toty",
    flag: "🇮🇹",
    fmVersion: "FM12",
    stats: { PAC: 12, FIN: 12, PAS: 17, DRI: 16, VIS: 17, STR: 10 },
  },
  {
    id: 23,
    name: "Javier Pastore",
    team: "Paris Saint-Germain",
    nationality: "Argentina",
    jerseyNumber: 27,
    age: 22,
    image: "https://r2.thesportsdb.com/images/media/player/cutout/haza2u1610454958.png",
    rating: 87,
    position: "CAM",
    cardType: "potm",
    flag: "🇦🇷",
    fmVersion: "FM12",
    stats: { PAC: 14, FIN: 15, PAS: 17, DRI: 18, VIS: 17, STR: 10 },
  },

  // ── FM 19 ──────────────────────────────────────────────────────────────
  {
    id: 7,
    name: "Marcus Rashford",
    team: "Manchester United",
    nationality: "England",
    jerseyNumber: 10,
    age: 20,
    image: "https://r2.thesportsdb.com/images/media/player/cutout/soi5zw1761512565.png",
    rating: 85,
    position: "LW",
    cardType: "potm",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    fmVersion: "FM19",
    stats: { PAC: 18, FIN: 15, PAS: 13, DRI: 16, VIS: 13, STR: 13 },
  },
  {
    id: 8,
    name: "Kylian Mbappé",
    team: "Paris Saint-Germain",
    nationality: "France",
    jerseyNumber: 29,
    age: 19,
    image: "https://r2.thesportsdb.com/images/media/player/cutout/h9u9vz1733653583.png",
    rating: 92,
    position: "ST",
    cardType: "toty",
    flag: "🇫🇷",
    fmVersion: "FM19",
    stats: { PAC: 20, FIN: 17, PAS: 14, DRI: 18, VIS: 15, STR: 13 },
  },
  {
    id: 9,
    name: "Neymar Jr.",
    team: "Paris Saint-Germain",
    nationality: "Brazil",
    jerseyNumber: 10,
    age: 26,
    image: "https://r2.thesportsdb.com/images/media/player/cutout/av4ar01767782947.png",
    rating: 93,
    position: "LW",
    cardType: "gold",
    flag: "🇧🇷",
    fmVersion: "FM19",
    stats: { PAC: 17, FIN: 17, PAS: 17, DRI: 20, VIS: 18, STR: 11 },
  },
  {
    id: 10,
    name: "Edinson Cavani",
    team: "Paris Saint-Germain",
    nationality: "Uruguay",
    jerseyNumber: 9,
    age: 31,
    image: "https://r2.thesportsdb.com/images/media/player/cutout/xf3lty1750043968.png",
    rating: 89,
    position: "ST",
    cardType: "hero",
    flag: "🇺🇾",
    fmVersion: "FM19",
    stats: { PAC: 16, FIN: 19, PAS: 13, DRI: 15, VIS: 14, STR: 15 },
  },
  {
    id: 11,
    name: "Kai Havertz",
    team: "Bayer Leverkusen",
    nationality: "Germany",
    jerseyNumber: 29,
    age: 19,
    image: "https://r2.thesportsdb.com/images/media/player/cutout/hem4r91694204364.png",
    rating: 79,
    position: "CAM",
    cardType: "wonderkid",
    flag: "🇩🇪",
    fmVersion: "FM19",
    stats: { PAC: 13, FIN: 14, PAS: 15, DRI: 15, VIS: 16, STR: 12 },
  },

  // ── FM 20 ──────────────────────────────────────────────────────────────
  {
    id: 12,
    name: "Rayan Cherki",
    team: "Olympique Lyonnais",
    nationality: "France",
    jerseyNumber: 18,
    age: 16,
    image: "https://r2.thesportsdb.com/images/media/player/cutout/emcyjy1769182115.png",
    rating: 73,
    position: "CAM",
    cardType: "wonderkid",
    flag: "🇫🇷",
    fmVersion: "FM20",
    stats: { PAC: 14, FIN: 14, PAS: 13, DRI: 17, VIS: 16, STR: 7 },
  },
  {
    id: 13,
    name: "Calvin Stengs",
    team: "AZ Alkmaar",
    nationality: "Netherlands",
    jerseyNumber: 7,
    age: 20,
    image: "https://r2.thesportsdb.com/images/media/player/cutout/4mn7ye1764189070.png",
    rating: 76,
    position: "RW",
    cardType: "wonderkid",
    flag: "🇳🇱",
    fmVersion: "FM20",
    stats: { PAC: 17, FIN: 14, PAS: 14, DRI: 17, VIS: 15, STR: 10 },
  },
  {
    id: 14,
    name: "Nicolò Zaniolo",
    team: "AS Roma",
    nationality: "Italy",
    jerseyNumber: 22,
    age: 20,
    image: "https://r2.thesportsdb.com/images/media/player/cutout/eh88s41764172604.png",
    rating: 80,
    position: "CAM",
    cardType: "potm",
    flag: "🇮🇹",
    fmVersion: "FM20",
    stats: { PAC: 15, FIN: 14, PAS: 14, DRI: 16, VIS: 15, STR: 14 },
  },
  {
    id: 15,
    name: "Jeremie Frimpong",
    team: "Celtic FC",
    nationality: "Netherlands",
    jerseyNumber: 67,
    age: 19,
    image: "https://r2.thesportsdb.com/images/media/player/cutout/ehf7fi1757088020.png",
    rating: 73,
    position: "RB",
    cardType: "wonderkid",
    flag: "🇳🇱",
    fmVersion: "FM20",
    stats: { PAC: 19, FIN: 11, PAS: 12, DRI: 16, VIS: 12, STR: 11 },
  },
  {
    id: 16,
    name: "Fábio Silva",
    team: "FC Porto",
    nationality: "Portugal",
    jerseyNumber: 9,
    age: 18,
    image: "https://r2.thesportsdb.com/images/media/player/cutout/qgss7i1762964939.png",
    rating: 71,
    position: "ST",
    cardType: "wonderkid",
    flag: "🇵🇹",
    fmVersion: "FM20",
    stats: { PAC: 14, FIN: 14, PAS: 12, DRI: 14, VIS: 13, STR: 13 },
  },

  // ── FM 21 / 22 ─────────────────────────────────────────────────────────
  {
    id: 17,
    name: "Nuno Mendes",
    team: "Sporting CP",
    nationality: "Portugal",
    jerseyNumber: 19,
    age: 18,
    image: "https://r2.thesportsdb.com/images/media/player/cutout/zhdk3h1766335452.png",
    rating: 77,
    position: "LB",
    cardType: "wonderkid",
    flag: "🇵🇹",
    fmVersion: "FM21",
    stats: { PAC: 18, FIN: 10, PAS: 14, DRI: 16, VIS: 13, STR: 13 },
  },
  {
    id: 18,
    name: "Gabriel Menino",
    team: "Palmeiras",
    nationality: "Brazil",
    jerseyNumber: 25,
    age: 19,
    image: "https://r2.thesportsdb.com/images/media/player/cutout/gcr2x21770031741.png",
    rating: 75,
    position: "CM",
    cardType: "wonderkid",
    flag: "🇧🇷",
    fmVersion: "FM21",
    stats: { PAC: 15, FIN: 13, PAS: 15, DRI: 15, VIS: 14, STR: 13 },
  },
  {
    id: 19,
    name: "Jean-Clair Todibo",
    team: "OGC Nice",
    nationality: "France",
    jerseyNumber: 5,
    age: 21,
    image: "https://r2.thesportsdb.com/images/media/player/cutout/2azc1l1756984568.png",
    rating: 77,
    position: "CB",
    cardType: "silver",
    flag: "🇫🇷",
    fmVersion: "FM22",
    stats: { PAC: 14, FIN: 8, PAS: 13, DRI: 13, VIS: 12, STR: 16 },
  },
  {
    id: 20,
    name: "Antonio Blanco",
    team: "Real Madrid B",
    nationality: "Spain",
    jerseyNumber: 14,
    age: 20,
    image: "https://r2.thesportsdb.com/images/media/player/cutout/6ritan1762352952.png",
    rating: 71,
    position: "DM",
    cardType: "wonderkid",
    flag: "🇪🇸",
    fmVersion: "FM22",
    stats: { PAC: 12, FIN: 11, PAS: 14, DRI: 14, VIS: 14, STR: 13 },
  },
  {
    id: 21,
    name: "Yaser Asprilla",
    team: "Watford FC",
    nationality: "Colombia",
    jerseyNumber: 17,
    age: 18,
    image: "https://www.thesportsdb.com/images/media/player/cutout/zhugc41773916009.png",
    rating: 73,
    position: "RW",
    cardType: "wonderkid",
    flag: "🇨🇴",
    fmVersion: "FM22",
    stats: { PAC: 18, FIN: 13, PAS: 13, DRI: 16, VIS: 14, STR: 11 },
  },
];

export default players;
